#dev config

registry:
# Docker registry url
  url: 'http://localhost:5001/v2/'
  name: 'hub.devspire.com.au'
  # with this config the user will not see all the available repos in docker-registry-web
  show-permitted-repo-only: true
  auth:
    enabled: true
    #issuer: 'xxx'
    key: ssl/key-dec.pem